version: "3"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - "27017:27017"
        volumes:
            - /data/db
        networks:
            - mongo_net
networks:
    mongo_net:
        driver: bridge